list= [23,43,54,32,2,4,234,5,23,23]
print(len(list)) 
print("Maxixmum list = ", max(list)) 
print("Minimun list = ", min(list)) 
list.append(1223) 
print(list) 
print("Sorting = ", list.sort())  
print(list)
print("Reverse Sorting =",list.sort(reverse=True))  
print(list)
print("Pop = ", list.pop()) 
list.insert(5,"fddf")  
print(list)
list.remove()
print(list) 
print(list.count(2)) 
list.pop(4) 
print(list)